apps/courses/urls.py
from django.conf.urls import url,include
from .views import CourseListView,CourseDetailView,CourseLearnView,CourseCommentView,AddCommentView
urlpatterns = [
    # 课程机构首页
    url(r'^list/',CourseListView.as_view(), name="course_list"),
    #课程详情页
    url(r'^detail(?P<course_id>\d+)/',CourseDetailView.as_view(), name="course_detail"),
    #  章节信息
    url(r'^learn(?P<course_id>\d+)/', CourseLearnView.as_view(), name="course_learn"),
    #课程评论
    url(r'^comment(?P<course_id>\d+)/', CourseCommentView.as_view(), name="course_comment"),
    #添加评论
    url(r'^addcomment',AddCommentView.as_view(), name="addcomment"),

]

apps/operation/urls.py
from django.conf.urls import url,include

urlpatterns = [
#     课程机构首页
    url(r'^listr/', name="org_list"),
]

apps/orgnization/urls.py
from django.conf.urls import url,include
from .views import Orglistview,UserAskView,Org_homeView,Org_CourseListViwe,\
    Org_DescView,Org_TeacherView,UserFavoriteView,TeacherlistView,TeacherDetailView
urlpatterns = [
    # 课程机构首页
    url(r'^listr/',Orglistview.as_view(), name="org_list"),
    # 教师首页
    url(r'^teacher_listr/', TeacherlistView.as_view(), name="org_teacher_list"),
    # 教师详情页
    url(r'^teacher_detail/(?P<teacher_id>\d+)', TeacherDetailView.as_view(), name="org_teacher_detail"),
    url(r'^add/',UserAskView.as_view(), name="add"),
    # 机构详情页
    url(r'^home/(?P<org_id>\d+)/$', Org_homeView.as_view(), name="org_home"),
#     机构课程列表页
    url(r'^courses/(?P<org_id>\d+)/', Org_CourseListViwe.as_view(), name="org_courses"),
#    机构介绍页
    url(r'^desc/(?P<org_id>\d+)/', Org_DescView.as_view(), name="org_desc"),
#   讲师页
    url(r'^teacher/(?P<org_id>\d+)/', Org_TeacherView.as_view(), name="org_teacher"),
# 用户收藏
    url(r'^addfav/',UserFavoriteView.as_view(),name="adfav"),
]

apps/users/urls.py
from django.conf.urls import url,include
from .views import UserListView,UserLoadImageView,UpLoadPwdView,\
                    SendEmailView,UpDataEmailView,UpdataInfoView,\
                    UserCourseView,UserFavOrgView,UserFavTeacherView,\
                    UserFavCourseView,UserMessageView

urlpatterns = [
    # 课程机构首页
    url(r'^list/',UserListView.as_view(), name="user_list"),
    #用户头像
    url(r'^upload/image/', UserLoadImageView.as_view(), name="user_uploadimage"),
    #用户修改密码
    url(r'^upload/pwd/', UpLoadPwdView.as_view(), name="user_uploadpwd"),
    #发送邮箱验证码
    url(r'^send/email/', SendEmailView.as_view(), name="sendemail"),
    #修改邮箱
    url(r'^updata/email/', UpDataEmailView.as_view(), name="updatamail"),
    #修改用户信息
    url(r'^updata/info/', UpdataInfoView.as_view(), name="updatainfo"),
    #用户课程
    url(r'^usercourses/', UserCourseView.as_view(), name="usercourses"),
    #用户收藏机构
    url(r'^userfavorg/', UserFavOrgView.as_view(), name="userfavorg"),
    #用户收藏教师
    url(r'^userfavteacher/', UserFavTeacherView.as_view(), name="userfavteacher"),
    #用户收藏课程
    url(r'^userfavcourse/', UserFavCourseView.as_view(), name="userfavcourse"),
    #用户消息队列
    url(r'^usermessage/', UserMessageView.as_view(), name="usermessage"),



]

s1mxonline/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from users.views import UserLogin,RegisterView,Activeuserview,UserLogoutView,IndexView
import xadmin
from django.views.generic import TemplateView
from orgnization.views import Orglistview,TeacherlistView
from django.views.static import serve
from s1mxonline.settings import MEDIA_ROOT
urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^index/', IndexView.as_view(),name="index"),
    url(r'^login/',UserLogin.as_view(),name="login"),
    # 退出登录
    url(r'^logout/', UserLogoutView.as_view(), name="logout"),
    url(r'^register/',RegisterView.as_view(),name="register"),
    # 拿到随机字符串
    url(r'^captcha/', include("captcha.urls")),
    url(r'^active/(?P<active_code>.*)/',Activeuserview.as_view(),name="active"),
#     配置个人中心页面
    url(r'^user/', include("users.urls", namespace="user")),
# 机构相关URL配置
    url(r'^orglistr/',include("orgnization.urls",namespace="org")),
# 课程相关URL的配置
    url(r'^courses/', include("courses.urls", namespace="courses")),

#  导入静态文件的处理方法
    url(r'^media/(?P<path>.*)',serve,{"document_root":MEDIA_ROOT}),
]

templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}课程机构列表 - 慕学在线网{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href='{% static "css/reset.css" %}'>
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block css %} {% endblock %}

</head>
<body>
<section class="headerwrap ">
    <header>
        <div class=" header">
            {% if request.user.is_authenticated %}
                <div class="top">
                    <div class="wp">
                        <div class="fl"><p>服务电话：<b>1853961297</b></p></div>
                        <div class="personal">
                            <dl class="user fr">
                                <dd>{{ request.user.username }}</dd>
                                <dt><img width="20" height="20" src="/media/{{ request.user.image }}"/>
                                </dt>
                            </dl>
                                {#                            显示未读消息数目#}
                             <a href="{% url 'user:usermessage' %}">
                            <div class="msg-num"><span id="MsgNum">{{ request.user.get_has_read }}</span></div>
                        </a>
                            <div class="userdetail">
                                <dl>
                                    <dt><img width="80" height="80"
                                             src="/media/{{ request.user.image }}"/></dt>
                                    <dd>
                                        <h2>>>>>>>>>></h2>
                                        <p>{{ request.user.username }}</p>
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="{% url 'user:user_list' %}">进入个人中心</a>
                                    <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
            {% else %}
                <div class="top">
                    <div class="wp">
                        <div class="fl"><p>服务电话：<b>1853961297</b></p></div>
                        <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a> -->
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a> -->

                    </div>
                </div>
            {% endif %}
            {# 			<div class="top">#}
            {#				<div class="wp">#}
            {#					<div class="fl"><p>服务电话：<b>1853961297</b></p></div>#}
            {#					<--登录后跳转-->#}
            {#						<div class="personal">#}
            {#                            <dl class="user fr">#}
            {#                                <dd>bobby<img class="down fr" src="/static/images/top_down.png"/></dd>#}
            {#                                <dt><img width="20" height="20" src="/static/media/image/2016/12/default_big_14.png"/></dt>#}
            {#                            </dl>#}
            {#                            <div class="userdetail">#}
            {#                            	<dl>#}
            {#	                                <dt><img width="80" height="80" src="/static/media/image/2016/12/default_big_14.png"/></dt>#}
            {#	                                <dd>#}
            {#	                                    <h2>django</h2>#}
            {#	                                    <p>bobby</p>#}
            {#	                                </dd>#}
            {#                                </dl>#}
            {#                                <div class="btn">#}
            {#	                                <a class="personcenter fl" href="usercenter-info.html">进入个人中心</a>#}
            {#	                                <a class="fr" href="/logout/">退出</a>#}
            {#                                </div>#}
            {#                            </div>#}
            {#                        </div>#}
            {##}
            {##}
            {#				</div>#}
            {#			</div>#}

            <div class="middle">
                <div class="wp">
                    <a href="index.html"><img class="fl" src="/static/images/logo.jpg"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课老师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="/static/images/search_btn.png"/>
                    </div>
                </div>
            </div>


            <nav>
                <div class="nav">
                    <div class="wp">
                        <ul>
                            <li {% if request.path == '/index/' %}class='active'{% endif %}><a href="{% url 'index' %}">首页</a>
                            </li>
                            <li {% if request.path|slice:'8' == '/courses' %}class='active'{% endif %}>
                                <a href="{% url 'courses:course_list' %}">
                                    公开课<img class="hot" src="/static/images/nav_hot.png">
                                </a>
                            </li>
                            <li {% if request.path|slice:'17' == '/orglistr/teacher' %}class='active'{% endif %}>
                                <a href="{% url 'org:org_teacher_list' %}">授课教师</a>
                            </li>
                            <li {% if request.path|slice:'15' == '/orglistr/listr' %}class='active'{% endif %}><a
                                    href="{% url 'org:org_list' %}">授课机构</a></li>
                        </ul>
                    </div>
                </div>
            </nav>

        </div>
    </header>
</section>
{% block content %}


{% endblock %}
{% block custom %}


{% endblock %}
<footer>
    <div class="footer">
        <div class="wp">
            <ul class="cont">
                <li class="logo"><a href=""><img src="{% static 'images/footlogo.png' %}"/></a></li>
                <li class="code"><img src="{% static 'images/code.jpg' %}"/>
                    <p class="center">扫描关注微信</p></li>
                <li class="third"><img class="fl" src="{% static 'images/tell.png' %}"/>
                    <p class="tell">33333333</p>
                    <p class="time">周一至周日 9:00-18:00</p></li>
            </ul>

        </div>
        <p class="line"></p>
        <div class="wp clear">
            <span class="fl">? 2016 www.projectsedu.com 慕学在线-在线学习交流平台 保留所有权利</span>
            <span class="fr">copyright ? 2016 ICP备案证书号：蜀ICP备xxxxx号-1</span>
        </div>
    </div>
</footer>

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
{% block js %} {% endblock %}

<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}" type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}" type="text/javascript"></script>
{% block script %}

{% endblock %}


</body>
</html>

templates/course-comment.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}公开课评论{% endblock %}
{% block css %}
     <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/aui.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
     <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
{% endblock %}

{% block content %}
        <section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="index.html">首页</a>></li>
                <li><a href="{% url 'courses:course_list' %}">公开课程</a>></li>
				<li><a href="{% url 'courses:course_detail' course.id %}">课程详情</a>></li>
                <li>课程评论</li>
			</ul>
		</div>
	</div>
</section>
       <div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ course.lear_time }}</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course.students }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
            <div class="content-wrap clearfix">
                <div class="content">
                    <div class="mod-tab-menu">
                        <ul class="course-menu clearfix">
                            <li><a class="ui-tabs-active " id="learnOn"  href="{% url 'courses:course_learn' course.id %}"><span>章节</span></a></li>
                            <li><a id="commentOn" class="active" href=""><span>评论</span></a></li>
                        </ul>
                    </div>

                    <!--发布评论-->
                    <div id="js-pub-container" class="issques clearfix js-form">
                        <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                            <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！"></textarea>
                        </div>
                        <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
                        <p class="global-errortip js-global-error"></p>

                    </div>
                    <div id="course_note">
                        <ul class="mod-post" id="comment-list">
                        {% for comment in all_comment %}
                            <li class="post-row">
                                <div class="media">
                                    <span target="_blank"><img src='/media/{{ comment.user.image }}' width='40' height='40' /></span>
                                </div>
                                <div class="bd">
                                    <div class="tit">
                                        <span target="_blank">{{ comment.user.username }}</span>
                                    </div>
                                    <p class="cnt">{{ comment.comment }}</p>
                                    <div class="footer clearfix">
                                        <span title="创建时间" class="l timeago">{{ comment.add_time }}</span>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}

                        </ul>
                    </div>

                </div>
                <div class="aside r">
                    <div class="bd">

                         <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                        {% for resource in resource %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>{{ resource.name }}</span>
                                <a href="media/{{ resource.download }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                        {% endfor %}
                        </ul>
                    </div>
                            <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <img src="/media/{{ course.teacher.image }}" width='80' height='80'>

        <span class="tit">
          <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
        </span>
                            <span class="job">xxx</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.you_know }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.teacher_tell }}</dd>
                            </dl>
                        </div>
                    </div>


                        <div class="cp-other-learned  js-comp-tabs">
                            <div class="cp-header clearfix">
                                <h2 class="cp-tit l">该课的同学还学过</h2>
                            </div>
                            <div class="cp-body">
                                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                    <!-- img 200 x 112 -->
                                    <ul class="other-list">
                                        <li class="curr">
                                            <a href="/view/85?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/57035ff200014b8a06000338-240-135.jpg" alt="Java入门第一季">
                                                <span class="name autowrap">Java入门第一季</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/view/110?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/5703604a0001694406000338-240-135.jpg" alt="Java入门第三季">
                                                <span class="name autowrap">Java入门第三季</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/view/124?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/570360620001390f06000338-240-135.jpg" alt="Java入门第二季">
                                                <span class="name autowrap">Java入门第二季</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/view/47?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/570765d90001bf1406000338-240-135.jpg" alt="Spring MVC起步">
                                                <span class="name autowrap">Spring MVC起步</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/view/36?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/53e1d0470001ad1e06000338-240-135.jpg" alt="JavaScript入门篇">
                                                <span class="name autowrap">JavaScript入门篇</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                    <ul class="other-list">
                                        <li class="curr">
                                            <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                                                <span class="name autowrap">Java工程师</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>    </div>
            </div>
            <div class="clear"></div>

        </div>

    </div>
</div>
{% endblock %}
{% block js %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}"  type="text/javascript"></script>
<script type="text/javascript">
    //添加评论
    $('#js-pl-submit').on('click', function(){
        var comments = $("#js-pl-textarea").val();
        if(comments == ""){
            alert("评论不能为空");
            return
        }
        $.ajax({
            cache: false,
            type: "POST",
            url:"{% url 'courses:addcomment' %}",
            data:{'course_id':{{ course.id }}, 'comments':comments},
            async: true,
            beforeSend:function(xhr, settings){
            {#     注意生成csrf—token#}
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            },
            success: function(data) {
                if(data.status == 'fail'){
                    if(data.msg == '用户未登录'){
                        window.location.href="/login/";
                    }else{
                        alert(data.msg)
                    }

                }else if(data.status == 'success'){
                    window.location.reload();//刷新当前页面.
                }
            }
        })
    });

</script>
{% endblock %}











templates/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的收藏{% endblock %}
{% block custom %}我的收藏{% endblock %}
{% block content %}

    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                       <ul class="tab_header messagehead">
                        <li class="active"><a href="{% url 'user:userfavorg' %}">课程机构</a> </li>
                        <li><a href="{% url 'user:userfavteacher' %}">授课教师 </a></li>
                        <li><a href="{% url 'user:userfavcourse' %}">公开课程</a></li>
                    </ul>`

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                    {% for course in course_list %}
                        <div class="module1_5 box">
                            <a href="{% url 'courses:course_detail'  course.id  %}">
                                <img width="214" height="190" src="/media/{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="course-detail.html"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.lear_time }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.courses_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>
                    {% endfor %}



                    </div>
                </div>
            </div>
        </div>
{% endblock %}



templates/usercenter-fav-org.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的收藏{% endblock %}
{% block custom %}我的收藏{% endblock %}
{% block content %}
        <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="active"><a href="{% url 'user:userfavorg' %}">课程机构</a> </li>
                        <li><a href="{% url 'user:userfavteacher' %}">授课教师 </a></li>
                        <li><a href="{% url 'user:userfavcourse' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for org in org_list %}

                    <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="org-detail-homepage.html">
                                    <img width="160" height="90" src="/media/{{ org.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="org-detail-homepage.html">{{ org.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">

                                    <img src="{% static 'images/authentication.png' %}"/>


                                    <img src="{% static 'images/gold.png' %}"/>

                                </div>
                                <span class="c8 clear">北京市</span>
                                <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
                            </dd>
                        </dl>
                    </div>

                    {% endfor %}


                </div>
            </div>
        </div>
{% endblock %}



templates/usercenter-message.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的消息{% endblock %}
{% block custom %}我的课程{% endblock %}
{% block content%}
    <div class="right" >
		<div class="personal_des Releasecont">
			<div class="head">
				<h1>我的消息</h1>
			</div>

		</div>
		<div class="personal_des permessage">
			<div class="head">
				<ul class="tab_header messagehead">
					<li class="active"><a href="/user/message/">个人消息</a> </li>
				</ul>


			</div>
			<div class="messagelist">
            {% for message in all_message.object_list %}
                    <div class="messages">
                        <div class="fr">
                            <div class="top"><span class="fl time">{{ message.add_time }}</span><span class="fr btn foldbtn"></span></div>
                            <p>
                                {{ message.message }}
                            </p>
                        </div>
                    </div>
            {% endfor%}



			</div>

			<div class="pageturn pagerright">
                <ul class="pagelist">

                            <li class="active"><a href="?page=1">1</a></li>





            </ul>
            </div>
		</div>

	</div>
{% endblock %}
